spring:
  profiles:
    active: prod
  application:
    name: careerconnect

  # Database 설정
  datasource:
    driver-class-name: com.mariadb.cj.jdbc.Driver
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}

  jpa:
    show-sql: true
    open-in-view: false
    properties:
      format_sql: true
      hibernate:
      dialect:
      ddl-auto: update

  flyway:
    url: ${DATABASE_URL}
    user: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
    locations: classpath:/db/migration/mariadb
    baselineOnMigrate: true
    enabled: true

#log 설정
logging:
  config: classpath:shoppingoo.xml
#  level:
#    root: DEBUG
#  pattern:
#     console: "%d %5p {%c} %m%n"

token:
  secret:
    key: SpringBootJWTHelperTokenSecretKeyValue123!@#
  access-token:
    plus-hour: 1
  refresh-token:
    plus-hour: 12


#swagger
springdoc:
  swagger-ui:
    path: /api-test  # swagger-ui 접근 경로에 대한 별칭, 해당 주소로 접속해도 http://localhost:8080/swagger-ui/index.html로 리다이렉션 됨.
    groups-order: DESC # path, query, body, response 순으로 출력
    tags-sorter: alpha # 태그를 알파벳 순으로 정렬
    operations-sorter: method  # delete - get - patch - post - put 순으로 정렬, alpha를 사용하면 알파벳 순으로 정렬 가능
  paths-to-match:
    - /api/** # swagger-ui에 표시할 api의 엔드포인트 패턴
